"""Test Table New Column

Revision ID: 19fd858d4b00
Revises: 0d28c23bf53c
Create Date: 2025-05-21 14:06:05.099237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fd858d4b00'
down_revision: Union[str, None] = '0d28c23bf53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test Table', sa.Column('newCol', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test Table', 'newCol')
    # ### end Alembic commands ###
