"""New column added to albums

Revision ID: 1d11e0930f73
Revises: 84b70ed30c38
Create Date: 2025-05-21 13:30:42.177256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d11e0930f73'
down_revision: Union[str, None] = '84b70ed30c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Albums', sa.Column('numberOne', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Albums', 'numberOne')
    # ### end Alembic commands ###
